
import { defineField, defineType } from "sanity";

export const playlist = defineType({
    name: "playlist",
    title: "Playlist",
    type: "document",   
    fields: [
        defineField({
            name: "title",
            type: "string",
        }),

        defineField({
            name: "slug",
            type: "slug", //slug is a type in sanity and unique identifier slugs for each startup will be generated by sanity automatically using 'title'
            options: { 
                source: "title"
            }
        }),
        defineField({
            name: "select",
            type: "array", //since the author of each startup will be of type author that we created
            of: [{type: 'reference', to:[{type: "startup"}]}]
        }),
       
    ],
})

