
import { defineField, defineType } from "sanity";

export const author = defineType({
    name: "startup",
    title: "Startup",
    type: "document",   
    fields: [
        defineField({
            name: "title",
            type: "string",
        }),

        defineField({
            name: "slug",
            type: "slug", //slug is a type in sanity and unique identifier slugs for each startup will be generated by sanity automatically using 'title'
            options: { 
                source: "title"
            }
        }),
        defineField({
            name: "author",
            type: "reference", //since the author of each startup will be of type author that we created
            to: { type: "author" }
        }),
        defineField({
            name: "views",
            type: "number",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "description",
            type: "text",
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: "category",
            type: "string",
            validation: (Rule) => Rule.required(),
        }),
       
    ],
    preview: {
        select: {
            title: "name" //allows to select author by name for preview
        },
    },
})

